from app.models.perfil import Perfil
from app.models.utilizador import Utilizador
from app.models.fornecedor import Fornecedor
from app.models.log_acesso import LogAcesso
from app.models.edificio import Edificio
from app.models.fracao import Fracao
from app.models.utilizador_fracao import UtilizadorFracao
from app.models.quota import Quota
from app.models.pagamento import Pagamento
from app.models.espaco_comum import EspacoComum
from app.models.estado_reserva import EstadoReserva
from app.models.reserva import Reserva
from app.models.categoria_avaria import CategoriaAvaria
from app.models.avaria import Avaria
from app.models.estado_ordem_trabalho import EstadoOrdemTrabalho
from app.models.ordem_trabalho import OrdemTrabalho
from app.models.categoria_despesa import CategoriaDespesa
from app.models.despesa import Despesa
from app.models.notificacao import Notificacao